<h1>a_tensor_initialization.py</h1>

In [1]:
import torch

In [2]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu') # [1,2,3]을 텐서로 생성, device는 텐서를 CPU에 할당하는 것을 의미함
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu() # t1 텐서를 CPU 메모리로 이동시킴, 이미 CPU에 있을 경우 아무런 변환 없이 반환
print("#" * 50, 1)

################################################## 1


In [4]:
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64 # 텐서의 데이터 타입 확인
print(t2.device)  # >>> cpu 
print(t2.requires_grad)  # >>> False # 기울기 보유 여뷰 -> 학습을 미분으로 하기 때문에 필요함
print(t2.size())  # torch.Size([3]) # 인자를 통해 차원의 size 조회 가능
print(t2.shape)  # torch.Size([3]) # 인덱스를 통해 차원의 size를 조회 가능

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [5]:
# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu() # 만약 GPU 사용이 가능하다면 위 주석 메소드로 cuda 환경에서 사용 가능
print("#" * 50, 2)

################################################## 2


In [6]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0 # 실수는 차원이 없음
print(a1.shape, a1.ndim) # shape은 shape를 출력하고, ndim은 차원을 출력함

torch.Size([]) 0


In [7]:
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [8]:
a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [9]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [10]:
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [11]:
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [12]:
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [13]:
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [14]:
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [15]:
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [16]:
a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

torch.Size([4, 1, 5]) 3


In [17]:
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
# 각 차원에서 일관된 크기가 아니므로 오류 발생
# 괄호의 중첩의 수가 텐서의 rank가 되며, 쉼표 수 + 1이 사이즈가 됨(만약 쉼표 이후 값이 없는 쉼표가 존재할 경우 쉼표 수 = 사이즈)

ValueError: expected sequence of length 3 at dim 3 (got 2)

<h1>취득한 기술 혹은 고찰 사항</h1>
기본적인 Shape이나 차원에 대해서 알게 되었으며, 텐서의 정보를 확인하는 기본적인 함수뿐만 아니라
텐서의 형태를 보고 차원이나 사이즈를 파악하는 방법을 많은 예제를 통하여 연습하고 학습함

<h1>b_tensor_initialization_copy.py</h1>

In [18]:
import torch
import numpy as np

In [19]:
# 리스트를 생성하고 텐서로 변환함
l1 = [1, 2, 3]
t1 = torch.Tensor(l1) #torch.Tensor는 기본으로 float32 타입의 텐서를 만듬
l2 = [1, 2, 3]
t2 = torch.tensor(l2) #torch.Tensor는 기본으로 입력 데이터의 데이터 타입을 유지함, 데이터 타입 명시 가능
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) #텐서 변환 시 가능하면 복사가 아닌 참조를 함

l1[0] = 100
l2[0] = 100
l3[0] = 100

#t1, t2는 복사를 하였음으로 기존 리스트의 값을 변경하였음에도 값이 수정이 되자 않음
#numpy가 아닌 파이썬의 리스트이므로 as_tensor을 사용하였음에도 참조가 아닌 복사가 됨
print(t1)
print(t2)
print(t3)
print("#" * 100)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################


In [20]:
# Numpy 배열로 텐서를 생성함
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)
l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)
l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4) 
print(t5) 
print(t6) # numpy array는 as_tensor 시 참조되므로 첫번째 값이 100으로 변경됨

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


<h1>취득한 기술 혹은 고찰 사항</h1>

tensor와 Tensor 함수를 통하여 텐서를 만드는 방법에 대해서 학습하고
as_tensor을 통해 참조를 통해 텐서를 만들어 메모리를 절약하는 방법에 대해서 학습함
특히 numpy array를 사용하여야 텐서를 참조하여 생성할 수 있다는 것이 중요한 내용이라고 생각함


<h1>c_tensor_initialization_constant_values.py</h1>

In [21]:
import torch

In [22]:
t1 = torch.ones(size=(5,))  # or torch.ones(5) size 크기의 1로 채워진 텐서 생성
t1_like = torch.ones_like(input=t1) # input 텐서와 동일한 크기와 속성을 가진 1로 채워진 텐서 생성
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [23]:
t2 = torch.zeros(size=(6,))  # or torch.zeros(6) size 크기의 0으로 채워진 텐서 생성
t2_like = torch.zeros_like(input=t2) # input 텐서와 동일한 크기와 속성을 가진 0로 채워진 텐서 생성
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [24]:
t3 = torch.empty(size=(4,))  # or torch.zeros(4) size 크기의 초기화되지 않은 텐서 생성
t3_like = torch.empty_like(input=t3) # input 텐서와 동일한 크기와 속성을 가진 초기화 안된 텐서 생성
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

tensor([1., 0., 0., 0.])
tensor([1., 0., 0., 0.])


In [25]:
t4 = torch.eye(n=3) # 단위 행렬을 생성하는 함수
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


<h1>취득한 기술 혹은 고찰 사항</h1>

기존 리스트나 numpy array 없이 텐서를 만드는 방법에 대해서 학습할 수 있었음

<h1>d_tensor_initialization_random_values.py</h1>

In [26]:
import torch

In [27]:
t1 = torch.randint(low=10, high=20, size=(1, 2)) # low, high 내 랜덤한 정수 값의 텐서 생성 
print(t1)
t2 = torch.rand(size=(1, 3)) # 균등 분포에서 랜덤한 정수 값의 텐서 생성
print(t2)
t3 = torch.randn(size=(1, 3)) # 정규 분포 형태의 랜덤한 정수 값의 텐서 생성
print(t3)
# mean은 평균 값, std는 표준편차에 따른 정규 분포 값 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2)) 
print(t4)
t5 = torch.linspace(start=0.0, end=5.0, steps=3) # start부터 end까지 일정하게 나뉜 텐서를 생성
print(t5)
t6 = torch.arange(5) # 범위 내 연속적인 정수 배열 생성
print(t6)

print("#" * 30)

tensor([[11, 18]])
tensor([[0.4361, 0.1371, 0.6101]])
tensor([[-2.2053,  0.6613, -0.7571]])
tensor([[11.2078,  8.9235],
        [10.1925,  9.1012],
        [ 9.4240, 10.2642]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################


In [28]:
torch.manual_seed(1729) # 토치의 랜덤 시드를 설정함, 시드에 따라 시작 시 동일한 결과 순서가 나옴
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


<h1>취득한 기술 혹은 고찰 사항</h1>

랜덤한 수를 만드는 방법에 대해서 학습함
특히 시드를 활용하여 랜덤한 수를 생성하지만, 그 랜덤한 수를 반복해서 활용할 수 있다는 것에 대해서 알게 되었음

<h1>e_tensor_type_conversion.py</h1>

In [29]:
import torch

In [30]:
a = torch.ones((2, 3)) # (2, 3) 크기의 값이 1인 텐서 생성 기본 타입은 float32
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16) # int16 데이터 타입 (2, 3) 크기의 값이 1인 텐서 생성 
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20. # (2, 3) 크기인 0과 1 사이의 균등 분포의 실수로 채워진 텐서 생성
print(c)

d = b.to(torch.int32) # 주어진 타입으로 텐서의 데이터 타입을 변환함
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [31]:
# ones 함수는 1로 채워진 텐서이며, zeros 함수는 0으로 채워진 텐서임 기본 타입은 float32
double_d = torch.ones(10, 2, dtype=torch.double) 
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double) # 0으로 채워진 텐서 생성 후 타입 변경
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double) # 데이터 타입이 변경됨
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [32]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


torch.float64


<h1>취득한 기술 혹은 고찰 사항</h1>

텐서의 형변환에 대해서 학습함
생성 시 인자를 활용하는 방법, 함수를 이용하는 방법, to 함수를 통하여 형변환하는 방법에 대해서 학습함

<h1>f_tensor_operations.py</h1>

In [33]:
import torch

In [34]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2) # 두 텐서를 덧셈을 함
t4 = t1 + t2 # add 함수와 동일한 덧셈 동작을 함
print(t3)
print(t4)

print("#" * 30)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################


In [35]:
t5 = torch.sub(t1, t2) # 두 텐서를 뺄셈을 함
t6 = t1 - t2 # sub 함수와 동일한 뺄셈 동작을 함
print(t5)
print(t6)

print("#" * 30)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################


In [36]:
t7 = torch.mul(t1, t2) # 두 텐서를 곱셈함
t8 = t1 * t2 # mul 함수와 동일한 곱셈 동작을 함
print(t7)
print(t8)

print("#" * 30)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################


In [37]:
t9 = torch.div(t1, t2) # 두 텐서를 나눗셈함
t10 = t1 / t2 # div 함수와 동일한 나눗셈 동작을 함
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


<h1>취득한 기술 혹은 고찰 사항</h1>

텐서의 기본 연산에 대해서 학습함
특히 행렬의 곱처럼 연산되는 것이 아닌, 행렬의 위치에 따라 연산이 된다는 것이 유의점이라고 생각이 들었음

<h1>g_tensor_operations_mm.py</h1>

In [38]:
import torch

In [39]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([]) # matmul은 행렬 곱셈을 함 

torch.Size([])


In [40]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

torch.Size([3])


In [41]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4) # 정규 분포에서 랜덤한 3차원 텐서를 생성함
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

torch.Size([10, 3])


In [42]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [43]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


import torch

In [44]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

tensor([2., 4., 6.])
################################################## 1


In [45]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) # broadcasting이 되고 있고 있음, 작은 것을 기준으로 큰 것에 맞추어서 행렬이 확장됨

print("#" * 50, 2)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2


In [46]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3


In [47]:
def normalize(x): # 이미지 픽셀 값이 0 ~ 255 사이 이므로 그 사이의 값으로 정규화함
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

torch.Size([3, 28, 28])
################################################## 4


In [48]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])
# 위 예제 역시 broadcasting이 되며 작은 것을 큰 것에 맞춰짐
print("#" * 50, 5)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5


In [49]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6


In [50]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7


In [51]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2) # 텐서에 제곱 연산을 함
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.]) # 값 범위 내 연속적인 실수 값을 가진 텐서를 생성
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp) # a의 요소를 exp 요소로 거듭제곱 연산을 함
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


<h1>취득한 기술 혹은 고찰 사항</h1>

텐서의 각종 행렬 연산과 broadcasting에 대해서 학습함
차원이 자동으로 맞춰지는 개념과, 텐서의 차원에 대한 개념을 학습하였지만
그 두개가 혼용되니 헷갈리는 부분이 많아서 어려움이 있었지만 예제를 여러 번을 실행해보면서 학습할 수 있었음

<h1>j_tensor_indexing_slicing.py</h1>

In [52]:
import torch

In [53]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# 텐서에서도 파이썬의 인덱싱과 슬라이싱을 활용할 수 있음
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1


In [54]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2


In [55]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1 # 텐서의 2열의 1번부터 3번 행 값을 1로 채움
print(y)

print(y[1:4, 1:4]) # 1번부터 3번행, 1번부터 3번열 부분을 슬라이싱함

print("#" * 50, 3)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3


In [56]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [57]:
z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


<h1>취득한 기술 혹은 고찰 사항</h1>

텐서에서도 인덱싱과 슬라이싱이 적용되는 것을 알 수 있었음
파이썬이 능숙하지 않아서, 슬라이싱에 대해서 어색한 점이 있었지만
예제를 실행해보면서 감을 잡을 수 있었음

<h1>k_tensor_reshaping.py</h1>

In [58]:
import torch

In [59]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2) # 텐서의 모양을 변경함, 연속적인 텐서에만 사용 가능하며 참조를 사용함
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6) #텐서의 모양을 변경하지만, 불연속적인 텐서일 경우 참조가 아닌 복사를 이용함
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [60]:
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4) # arange로 1차원 텐서 생성 후 텐서 모양을 변경함
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1


In [61]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,) # 크기가 1인 차원을 모두 제거함

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1) # 함수 인자인 0번 차원 값을 제거함
print(t7)
print(t8)

print("#" * 50, 2)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2


In [62]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1) # 함수 인자인 1번 위치에 새로운 차원을 추가함
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3) # (2, 3)에서 1번 위치에 차원을 추가하여 (2, 1, 3) 이 됨
print(t12, t12.shape)

print("#" * 50, 3)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3


In [63]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,) # 다차원 텐서를 1차원 텐서로 만듬

print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [64]:
# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1) # start_dim의 값 부터 평탄화를 함 
#(2, 2, 2) 텐서가 (2, 4)로 바뀜

print(t16)
print(t17)

print("#" * 50, 4)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4


In [65]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
# 텐서의 순서를 새롭게 지정함 아래에서는 2번->0번, 0번->1번, 1번->2번이 됨
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [66]:
# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
# 차원의 순서를 바꿈
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2) # 텐서의 두 차원을 교환함

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2) # 2차원 텐서의 행과 열을 바꿈 transpose를 2차원에서 실행한 것과 동일

print(t23)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


<h1>취득한 기술 혹은 고찰 사항</h1>

텐서의 shape를 바꾸는 각종 함수에 대해서 학습함
squeeze가 인자가 없으면 사이즈가 1인 차원을 삭제하고, 인자를 주어지면 인자의 차원이 지워진다는 것에 유의해야할 것 같음
차원의 shape가 데이터는 유지한 채 변하고, 펼쳐지고 순서가 바뀌는 함수가 많은데 이때 어떤 형태로 shape이 되어있고
데이터가 나열되어있을까라는 생각을 많이 해야할 것 같음

<h1>l_tensor_concat.py</h1>

In [67]:
import torch

In [68]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1) # 여러 텐서를 dim으로 선택한 차원에서 연결하여 하나의 텐서로 만듬, 사이즈만 변하고 차원은 변하지 않음
print(t4.shape)

print("#" * 50, 1)

torch.Size([2, 6, 3])
################################################## 1


In [69]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2


In [70]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3


In [71]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4


In [72]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


<h1>취득한 기술 혹은 고찰 사항</h1>

cat은 차원은 변하지 않고, 사이즈만 변한다는 것을 유의해야할 것 같음
추가로 탐색하여, concat은 동일한 기능이지만 이름만 다르게 파이토치에서 추후에 나온 함수라는데 나온 이유는
함수명의 직관성과 다른 프레임워크, 언어와 동일성이 가져오기 위함이라는 것을 추가적으로 알아봄

<h1>m_tensor_stacking.py</h1>

In [73]:
import torch

In [74]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0) # t1과 t2를 dim 번째 차원에 추가하여 합침, stack은 새로운 차원으로 확장하여 병합됨
# 결과값으로 (2, 3) -> (2, 2, 3)>이 됨
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
# t1과 t2에 새로운 차원을 unsqueeze로 추가하며, dim 번째에 cat 함수를 이용하여 이어붙임
# 2, 2, 3이 되어서 t3와 동일한 모양이 됨
print(t3.shape, t3.equal(t4))

torch.Size([2, 2, 3]) True


In [75]:
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

torch.Size([2, 2, 3]) True


In [76]:
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

torch.Size([2, 3, 2]) True
################################################## 1


In [77]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


<h1>취득한 기술 혹은 고찰 사항</h1>

stack에 대해서 학습을 함
stack과 cat의 차이점에 대해서 헷갈리지 않고 알아야 할 것 같음

<h1>n_tensor_vstack_hstack.py</h1>

In [78]:
import torch

In [79]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2)) # 각 텐서를 새로운 행으로 추가시킴 => 수직으로 병합함
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [80]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

In [81]:
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

torch.Size([2, 2, 3])


In [82]:
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

torch.Size([2, 2, 3])


In [83]:
t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1


In [84]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11)) # 텐서를 1차원 텐서로 연결함 => hstack은 수평으로 병합함
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])


In [85]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [86]:
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

torch.Size([2, 2, 3])


In [87]:
t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])

torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


<h1>취득한 기술 혹은 고찰 사항</h1>

vstack과 hstack에 대해서 학습하였으며 함수 명에 적혀있듯이 v와 h의 뜻을 잘 생각하고 헷갈리지 않게 사용해야할 것 같다.

<h1>숙제 후기</h1>

이전에는 파이썬에 대해 알고 있는 지식이 적을 뿐만 아니라, 파이토치 그리고 텐서에 대한 기본 개념과 함수에 대한 지식이 부족했다.</br>
하지만 이번 hw1_1 과제를 수행하면서 기본적인 파이토치와 텐서 그리고 파이썬에 동작에 대해서도 생각해보고 학습할 수 있었다.</br>
많은 예제를 접하면서 텐서의 모양을 변형시키고 수정하는 과정에서 같은 코드를 계속 복기해보는 등 어려움을 겪었으며 주피터 사용에도 미숙하여
힘든 점이 많았던 것 같다. 하지만 힘든 점을 해결하면서 얻는 점이 많았고 특강의 내용을 복기하면서 과제 진행하고 파이토치 예제를 많이 실행해보고 고찰하니
이제 텐서에 대해서 조금 알게 된 것 같아서 유의미했던 시간이었던 것 같다.